### ISSUE TITLE
Overwrite Permission Error Bug

### ISSUE THREAD

**Issue by AlisonJarvis** [jmbhughes/solarannotator#1]
Traceback (most recent call last):
  File "c:\users\aliso\appdata\local\continuum\anaconda3\lib\site-packages\solarannotator\gui.py", line 696, in file_save_as
    self.annotator.thmap.save(fname[0])
  File "c:\users\aliso\appdata\local\continuum\anaconda3\lib\site-packages\solarannotator\io.py", line 122, in save
    hdu.writeto(path, overwrite=True, checksum=True)
  File "c:\users\aliso\appdata\local\continuum\anaconda3\lib\site-packages\astropy\utils\decorators.py", line 521, in wrapper
    return function(*args, **kwargs)
  File "c:\users\aliso\appdata\local\continuum\anaconda3\lib\site-packages\astropy\io\fits\hdu\hdulist.py", line 919, in writeto
    fileobj = _File(fileobj, mode=mode, overwrite=overwrite)
  File "c:\users\aliso\appdata\local\continuum\anaconda3\lib\site-packages\astropy\utils\decorators.py", line 521, in wrapper
    return function(*args, **kwargs)
  File "c:\users\aliso\appdata\local\continuum\anaconda3\lib\site-packages\astropy\io\fits\file.py", line 178, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "c:\users\aliso\appdata\local\continuum\anaconda3\lib\site-packages\astropy\io\fits\file.py", line 544, in _open_filename
    self._overwrite_existing(overwrite, None, True)
  File "c:\users\aliso\appdata\local\continuum\anaconda3\lib\site-packages\astropy\io\fits\file.py", line 436, in _overwrite_existing
    os.remove(self.name)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:/Users/aliso/OneDrive/Documents/CIRESNOAA Space Weather/First Iteration Thematic Maps/20201128T043000Alison.fits'

**Comment by jmbhughes** [comment]
Happens when a file is already open and trying to save over.

**Comment by jmbhughes** [comment]
Closing because cannot recreate.
